Repository osuAkatsuki/bancho.py, pull requests merged in 2022-07, with the labels that each got.

#251 If no osu!api key is defined, use Kitsu's API to get beatmap metadata
  app/objects/beatmap.py
Labels: enhancement

#260 Add mod introduction achievements
  app/settings.py
  app/utils.py
  migrations/base.sql
  migrations/migrations.sql
Labels: enhancement

#257 Add db column to track when a user added map as a favourite; add redirect for beatmapset discussion page
  app/api/domains/osu.py
  app/settings.py
  migrations/base.sql
  migrations/migrations.sql
Labels: enhancement

#250 NGINX avatar serving
  app/api/domains/__init__.py
  app/api/domains/ava.py
  app/api/domains/osu.py
  app/api/init_api.py
  ext/nginx.conf
Labels: optimization

#262 feat: refactor client version validation upon login
  .env.example
  app/api/domains/cho.py
  app/settings.py
Labels: bug, enhancement
