Repository osuAkatsuki/bancho.py, pull requests merged in 2022-04, with the labels that each got.

#218 Fix OpenAPI docs not being generated
  app/api/init_api.py
Labels: documentation

#216 Add `api` subdomain and `Access-Control-Allow-Origin` header to nginx config
  ext/nginx.conf
Labels: bug

#230 made rmpriv set donor_end back to 0
  app/commands.py
Labels: bug

#229 Add donor_end to player object, use pytimeparse consistently
  app/api/domains/api.py
  app/commands.py
  app/constants/regexes.py
  app/objects/collections.py
  app/objects/player.py
Labels: enhancement
