Repository osuAkatsuki/bancho.py, pull requests merged in 2023-08, with the labels that each got.

#473 generate requirements lockfile in ci upon requirements change & update lockfile
  .github/workflows/lock-requirements.yaml
  Pipfile.lock
Labels: enhancement

#413 docs: link readme to wiki
  README.md
Labels: documentation

#474 Fix rosupp DTNC pp calculation meme
  app/usecases/performance.py
Labels: bug
