Repository osuAkatsuki/bancho.py, pull requests merged in 2023-03, with the labels that each got.

#367 refactor: move geolocation system (maxmind) to nginx layer
  .github/images/cf_geoloc.png
  Pipfile
  Pipfile.lock
  README.md
  app/api/domains/cho.py
  app/api/domains/osu.py
  app/api/init_api.py
  app/state/services.py
  ext/nginx.conf
  requirements-dev.txt
  requirements.txt
  tools/enable_geoip_module.sh
Labels: enhancement, dependencies, Priority 0

#398 fix: account for sv2 in mania acc calculation
  app/objects/score.py
Labels: bug

#320 feat: add `Dockerfile`; add `docker-compose`
  .env.example
  .github/images/ssl_cf_1.png
  .github/images/ssl_cf_10.png
  .github/images/ssl_cf_2.png
  .github/images/ssl_cf_3.png
  .github/images/ssl_cf_4.png
  .github/images/ssl_cf_5.png
  .github/images/ssl_cf_6.png
  .github/images/ssl_cf_7.png
  .github/images/ssl_cf_8.png
  .github/images/ssl_cf_9.png
  .gitignore
  Dockerfile
  Makefile
  README.md
  app/utils.py
  docker-compose.yml
  ext/nginx.conf.example
  main.py
  scripts/start_server.sh
  scripts/wait-for-it.sh
  tools/generate_cf_dns_records.sh
Labels: documentation, enhancement, code quality, dependencies
