Repository osuAkatsuki/bancho.py, pull requests merged in 2023-01, with the labels that each got.

#319 refactor: players repository (& unrelated refactoring that really shouldn't be in this pr)
  app/api/domains/api.py
  app/api/domains/cho.py
  app/api/domains/osu.py
  app/commands.py
  app/objects/clan.py
  app/objects/collections.py
  app/objects/match.py
  app/objects/player.py
  app/repositories/players.py
  app/state/services.py
  app/utils.py
Labels: bug, code quality

#321 refactor: stats repository
  app/api/domains/api.py
  app/api/domains/osu.py
  app/objects/player.py
  app/repositories/stats.py
Labels: code quality

#327 feat: clans repository
  app/commands.py
  app/objects/clan.py
  app/objects/collections.py
  app/repositories/clans.py
Labels: code quality

#328 feat: maps repo
  app/api/domains/osu.py
  app/commands.py
  app/objects/beatmap.py
  app/repositories/maps.py
Labels: code quality

#329 fix: various beatmap bugs
  app/api/domains/osu.py
  app/objects/beatmap.py
Labels: bug

#326 feat: scores repository
  app/api/domains/api.py
  app/api/domains/osu.py
  app/objects/score.py
  app/repositories/clans.py
  app/repositories/scores.py
Labels: code quality

#338 feat: achievements repo
  app/objects/collections.py
  app/repositories/achievements.py
Labels: code quality

#337 feat: channels repo
  app/objects/collections.py
  app/repositories/channels.py
Labels: code quality

#342 refactor: (finally) murder nullability of match chat channels
  app/api/domains/cho.py
  app/objects/collections.py
  app/objects/match.py
  app/settings.py
Labels: code quality

#344 refactor: match operators allowing accesses to slots
  app/commands.py
  app/objects/match.py
Labels: code quality

#345 [code-quality] Cleanup single character variable names
  app/api/domains/api.py
  app/api/domains/cho.py
  app/api/domains/osu.py
  app/bg_loops.py
  app/commands.py
  app/constants/mods.py
  app/objects/channel.py
  app/objects/clan.py
  app/objects/collections.py
  app/objects/match.py
  app/objects/player.py
  app/packets.py
Labels: code quality

#343 refactor: nullability at the top level for player's last np
  app/api/domains/cho.py
  app/commands.py
  app/objects/player.py
  app/objects/score.py
Labels: code quality

#354 chore: remove all walrus operator usage
  app/api/domains/api.py
  app/api/domains/cho.py
  app/api/domains/osu.py
  app/commands.py
  app/discord.py
  app/objects/beatmap.py
  app/objects/collections.py
  app/objects/match.py
  app/objects/player.py
  app/settings.py
  app/state/services.py
  app/state/sessions.py
  main.py
  tools/proxy.py
  tools/recalc.py
Labels: code quality

#359 fix: support empty server port in config
  app/settings.py
Labels: bug

#361 Fix not being able to pick converts maps in multiplayer
  app/api/domains/cho.py
Labels: bug

#364 refactor: api-v2 create basic players resource
  app/api/v1/__init__.py
  app/api/v2/__init__.py
  app/api/v2/common/json.py
  app/api/v2/common/responses.py
  app/api/v2/models/__init__.py
  app/api/v2/models/players.py
  app/api/v2/players.py
Labels: enhancement, code quality

#365 separate api v1 from v2; GET v2/players endpoints
  app/api/__init__.py
  app/api/domains/__init__.py
  app/api/init_api.py
  app/api/v1/__init__.py
  app/api/v1/api.py
  app/api/v2/__init__.py
  app/api/v2/common/json.py
  app/api/v2/common/responses.py
  app/api/v2/models/__init__.py
  app/api/v2/models/players.py
  app/api/v2/players.py
Labels: enhancement

#372 feat: v2 clans api (get calls only)
  app/api/v2/__init__.py
  app/api/v2/clans.py
  app/api/v2/models/clans.py
  app/repositories/clans.py
Labels: enhancement

#360 Add reason to unsilence command
  app/commands.py
  app/objects/player.py
Labels: enhancement

#375 feat: v2 api add GET /players/{player_id}/status
  app/api/v2/models/players.py
  app/api/v2/players.py
Labels: enhancement

#373 feat: v2 maps api (get calls only)
  app/api/v2/__init__.py
  app/api/v2/maps.py
  app/api/v2/models/maps.py
  app/repositories/maps.py
Labels: enhancement

#376 feat: v2 player stats api
  app/api/v2/clans.py
  app/api/v2/models/players.py
  app/api/v2/players.py
Labels: enhancement

#380 docs: add issue and pr templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/custom.md
  .github/pull_request_template.md
  .github/workflows/require-checklist.yaml
Labels: documentation

#382 tools: enable pre-commit for dev install; add lint
  .github/pull_request_template.md
  Makefile
Labels: documentation, enhancement

#383 docs: Add code of conduct
  .github/CODE_OF_CONDUCT.md
Labels: documentation

#381 docs: add `SECURITY.md`
  .github/SECURITY.md
Labels: documentation

#363 refactor: use stats repo for score submission stats update
  app/api/domains/osu.py
Labels: code quality

#384 fix: gamemode related bugs in recalc script
  tools/recalc.py
Labels: bug

#362 refactor: reorganize code in score submission
  app/api/domains/osu.py
Labels: code quality
