Repository osuAkatsuki/bancho.py, pull requests merged in 2023-04, with the labels that each got.

#422 interactive ui for online players & matches on GET /c.ppy.sh page
  app/api/domains/cho.py
Labels: enhancement

#370 fix: `!server` command requirements.txt parsing
  app/commands.py
Labels: bug

#349 feat: rename `get_apikey` to `apikey`; provide API key via browser
  app/commands.py
Labels: enhancement

#368 refactor: generalize beatmap mirror code
  .env.example
  app/api/domains/map.py
  app/api/domains/osu.py
  app/commands.py
  app/settings.py
Labels: code quality

#348 feat: add `/calculate_pp` API endpoint; extend performance usecase data
  app/api/domains/cho.py
  app/api/v1/api.py
  app/commands.py
  app/objects/score.py
  app/usecases/performance.py
Labels: enhancement

#352 feat: support all judgements in pp calculation
  tools/recalc.py
Labels: bug

#430 fix: only allow one space to be stripped from score submission username
  app/api/domains/osu.py
Labels: bug

#427 fix typing errors in performance calc from #348
  app/api/v1/api.py
  app/usecases/performance.py
Labels: code quality

#425 add separate config for docker and manual install
  README.md
  docker.env.example
  ext/docker-nginx.conf.example
  ext/manual-nginx.conf.example
  manual.env.example
Labels: enhancement
