Repository osuAkatsuki/bancho.py, pull requests merged in 2023-09, with the labels that each got.

#490 chore: upgrade to python 3.11; upgrade redis library; upgrade databases
  .github/workflows/lock-requirements.yaml
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  app/api/domains/cho.py
  app/api/domains/osu.py
  app/api/init_api.py
  app/api/v1/api.py
  app/api/v2/common/responses.py
  app/api/v2/maps.py
  app/api/v2/models/__init__.py
  app/api/v2/models/players.py
  app/api/v2/players.py
  app/api/v2/scores.py
  app/commands.py
  app/discord.py
  app/logging.py
  app/objects/achievement.py
  app/objects/beatmap.py
  app/objects/channel.py
  app/objects/clan.py
  app/objects/collections.py
  app/objects/match.py
  app/objects/menu.py
  app/objects/player.py
  app/objects/score.py
  app/packets.py
  app/repositories/achievements.py
  app/repositories/channels.py
  app/repositories/clans.py
  app/repositories/maps.py
  app/repositories/players.py
  app/repositories/scores.py
  app/repositories/stats.py
  app/state/cache.py
  app/state/services.py
  app/usecases/performance.py
  app/utils.py
  docker/banchopy/Dockerfile
  main.py
  requirements-dev.txt
  requirements.txt
  tools/migrate_logs.py
  tools/newstats.py
  tools/recalc.py
Labels: enhancement

#499 impl: implement unset pattern
  app/_typing.py
  app/objects/collections.py
  app/repositories/achievements.py
  app/repositories/channels.py
  app/repositories/clans.py
  app/repositories/maps.py
  app/repositories/players.py
  app/repositories/scores.py
  app/repositories/stats.py
Labels: enhancement, code quality

#501 Fix typing errors & introduce mypy as a required CI step
  .github/workflows/lint.yaml
  Makefile
  Pipfile
  Pipfile.lock
  app/_typing.py
  app/api/domains/cho.py
  app/api/domains/map.py
  app/api/domains/osu.py
  app/api/v1/api.py
  app/api/v2/common/responses.py
  app/api/v2/models/__init__.py
  app/bg_loops.py
  app/commands.py
  app/constants/mods.py
  app/discord.py
  app/logging.py
  app/objects/achievement.py
  app/objects/beatmap.py
  app/objects/collections.py
  app/objects/match.py
  app/objects/player.py
  app/objects/score.py
  app/packets.py
  app/repositories/__init__.py
  app/repositories/achievements.py
  app/repositories/channels.py
  app/repositories/clans.py
  app/repositories/maps.py
  app/repositories/players.py
  app/repositories/scores.py
  app/repositories/stats.py
  app/settings.py
  app/state/__init__.py
  app/state/services.py
  app/state/sessions.py
  app/usecases/performance.py
  app/utils.py
  main.py
  mypy.ini
  requirements-dev.txt
  requirements.txt
  tools/newstats.py
  tools/recalc.py
Labels: bug, code quality

#504 Swap aiohttp out in preference of httpx
  Pipfile
  Pipfile.lock
  app/api/domains/cho.py
  app/api/domains/osu.py
  app/api/init_api.py
  app/discord.py
  app/objects/beatmap.py
  app/state/services.py
  requirements-dev.txt
  requirements.txt
  tools/recalc.py
Labels: code quality, dependencies

#489 refactor: ingame_logins repository
  app/api/domains/cho.py
  app/repositories/ingame_logins.py
Labels: enhancement, code quality

#507 Fix mypy discovery & all type errors across source
  Pipfile
  Pipfile.lock
  app/api/domains/cho.py
  app/api/domains/osu.py
  app/api/init_api.py
  app/api/v2/clans.py
  app/api/v2/common/responses.py
  app/api/v2/maps.py
  app/api/v2/players.py
  app/api/v2/scores.py
  app/commands.py
  app/repositories/ingame_logins.py
  mypy.ini
  requirements-dev.txt
Labels: bug, code quality

#477 Set an absolute limit of 1 day on beatmaps cache; generalize some code
  app/objects/beatmap.py
Labels: bug

#513 Unify manual & docker execution modes into a single docker-backed runtime
  .env.example
  .github/docs/wiki/Read-before-setting-up.md
  .github/docs/wiki/Setting-up-(Docker).md
  .github/docs/wiki/Setting-up-(Manual).md
  .github/docs/wiki/Setting-up.md
  .github/docs/wiki/_Sidebar.md
  .github/docs/wiki/locale/de-DE/Read-before-setting-up-de-DE.md
  .github/docs/wiki/locale/de-DE/Setting-up-(Docker)-de-DE.md
  .github/docs/wiki/locale/de-DE/Setting-up-(Manual)-de-DE.md
  .github/docs/wiki/locale/de-DE/Setting-up-de-DE.md
  .github/docs/wiki/locale/de-DE/_Sidebar.md
  .github/docs/wiki/locale/zh-CN/Read-before-setting-up-zh-CN.md
  .github/docs/wiki/locale/zh-CN/Setting-up-(Docker)-zh-CN.md
  .github/docs/wiki/locale/zh-CN/Setting-up-(Manual)-zh-CN.md
  .github/docs/wiki/locale/zh-CN/Setting-up-zh-CN.md
  .github/docs/wiki/locale/zh-CN/_Sidebar.md
  .gitignore
  Dockerfile
  Makefile
  app/api/init_api.py
  app/objects/collections.py
  app/settings.py
  app/settings_utils.py
  docker-compose.yml
  docker/banchopy/Dockerfile
  docker/nginx-with-geoip2/Dockerfile
  docker/nginx-with-geoip2/main.conf
  docker/nginx.conf
  ext/nginx.conf.example
  main.py
  manual.env.example
  requirements-dev.txt
  requirements.txt
  scripts/install-nginx-config.sh
  scripts/start_required_services.sh
  scripts/start_server.sh
Labels: documentation, code quality, dependencies

#519 feat: add docker build/push action
  .github/workflows/docker-build.yaml
Labels: enhancement

#520 Add mypy pydantic plugin
  mypy.ini
Labels: enhancement, code quality

#535 chore: remove experimental menu system
  .github/docs/wiki/Project-structure.md
  .github/docs/wiki/locale/de-DE/Project-structure-de-DE.md
  .github/docs/wiki/locale/zh-CN/Project-structure-zh-CN.md
  app/api/domains/cho.py
  app/commands.py
  app/objects/__init__.py
  app/objects/menu.py
  app/objects/player.py
Labels: code quality
