Repository osuAkatsuki/bancho.py, pull requests merged in 2023-07, with the labels that each got.

#438 fix: add return value for `/web/osu-addfavourite.php`
  app/api/domains/osu.py
Labels: ready-for-merge

#424 chore: Change nginx docker image to the official one with geoip2 support
  docker-compose.yml
  docker.env.example
  docker/banchopy/Dockerfile
  docker/nginx-with-geoip2/Dockerfile
  docker/nginx-with-geoip2/main.conf
  ext/docker-nginx.conf.example
Labels: enhancement, ready-for-merge

#460 chore: add wiki to `.github/docs/wiki`
  .github/docs/wiki/1.-Code-Styling.md
  .github/docs/wiki/2.-Project-Structure.md
  .github/docs/wiki/3.-Read-before-setting-up.md
  .github/docs/wiki/4.-Setting-Up-(Docker).md
  .github/docs/wiki/5.-Setting-Up-(Manual).md
  .github/docs/wiki/6.-Post-Set-Up.md
  .github/docs/wiki/Home.md
  .github/docs/wiki/_Footer.md
Labels: documentation, ready-for-merge

#419 chore: Add bidirectional sync between .github/docs/wiki and wiki
  .github/docs/wiki/6.-Post-Set-Up.md
  .github/workflows/sync-docs.yaml
Labels: documentation, enhancement, ready-for-merge

#463 chore: (Docker) Use env variables in the nginx config for port and domain
  .github/docs/wiki/Setting-up-(Docker).md
  .github/docs/wiki/Setting-up-(Manual).md
  .github/docs/wiki/locale/de-DE/Setting-up-(Docker)-de-DE.md
  .github/docs/wiki/locale/de-DE/Setting-up-(Manual)-de-DE.md
  .github/docs/wiki/locale/zh-CN/Setting-up-(Docker)-zh-CN.md
  .github/docs/wiki/locale/zh-CN/Setting-up-(Manual)-zh-CN.md
  docker-compose.yml
  docker/nginx.conf
  ext/nginx.conf.example
Labels: enhancement
