Repository osuAkatsuki/bancho.py, pull requests merged in 2024-02, with the labels that each got.

#557 Per-checksum score submission locks to prevent score duplicates
  app/api/domains/osu.py
  app/state/__init__.py
Labels: bug

#486 refactor: comments repository
  app/api/domains/osu.py
  app/repositories/comments.py
Labels: enhancement, code quality

#484 refactor: logs repository
  app/commands.py
  app/objects/player.py
  app/repositories/logs.py
Labels: enhancement, code quality

#565 Do or remove TODOs throughout the code
  app/api/domains/cho.py
  app/api/domains/osu.py
  app/api/middlewares.py
  app/api/v1/api.py
  app/api/v2/common/responses.py
  app/commands.py
  app/constants/mods.py
  app/logging.py
  app/objects/beatmap.py
  app/objects/match.py
  app/packets.py
  app/utils.py
  main.py
Labels: enhancement, code quality

#564 osu! client login refactoring, fixes, cleanup
  app/api/domains/cho.py
  app/objects/player.py
  app/packets.py
  tests/unit/test_packets.py
Labels: code quality

#508 Tests running in CI & score submission integration test
  .github/workflows/lock-requirements.yaml
  .github/workflows/require-checklist.yaml
  .github/workflows/sync-docs.yaml
  .github/workflows/test.yaml
  Makefile
  Pipfile
  Pipfile.lock
  app/api/domains/osu.py
  app/commands.py
  app/encryption.py
  app/objects/beatmap.py
  app/settings.py
  app/state/services.py
  docker-compose.yml
  requirements-dev.txt
  requirements.txt
  scripts/install-nginx-config.sh
  scripts/run-tests.sh
  testing/__init__.py
  testing/sample_data/__init__.py
  testing/sample_data/sample_beatmap_data.py
  testing/sample_data/vivid_osu_file.osu
  tests/conftest.py
  tests/integration/domains/osu_test.py
  tests/unit/packets_test.py
Labels: enhancement

#487 refactor: mails repository
  app/api/domains/cho.py
  app/api/domains/osu.py
  app/repositories/mail.py
Labels: enhancement, code quality

#578 fix: only run the push portion of the lint action when on master
  .github/workflows/lint.yaml
Labels: code quality

#579 chore: switch to poetry and remove requirements.txt
  .github/docs/wiki/Setting-up.md
  .github/docs/wiki/locale/de-DE/Setting-up-de-DE.md
  .github/docs/wiki/locale/zh-CN/Setting-up-zh-CN.md
  .github/workflows/lint.yaml
  .github/workflows/lock-requirements.yaml
  .gitignore
  Dockerfile
  Makefile
  Pipfile
  Pipfile.lock
  app/settings.py
  poetry.lock
  pyproject.toml
  requirements-dev.txt
  requirements.txt
Labels: bug, code quality, dependencies

#581 chore: migrate all configs to pyproject.toml
  .isort.cfg
  mypy.ini
  pyproject.toml
  tests/pytest.ini
Labels: code quality

#559 Refactor: More clearly divide responsibilities of widely used `ensure_local_osu_file` function
  app/api/domains/cho.py
  app/api/domains/osu.py
  app/api/v1/api.py
  app/commands.py
  app/objects/beatmap.py
  app/objects/score.py
  tools/recalc.py
Labels: code quality

#485 refactor: map_requests repository
  app/commands.py
  app/repositories/map_requests.py
Labels: enhancement, code quality

#585 Reduce duplication issues with map nomination requests
  app/commands.py
  app/repositories/map_requests.py
Labels: bug

#593 Isolated global state for each run of a test suite
  .github/workflows/test.yaml
  Dockerfile
  Makefile
  app/api/init_api.py
  app/utils.py
  docker-compose.test.yml
  main.py
  scripts/run-tests.sh
  tests/conftest.py
Labels: enhancement

#595 refactor: client_hashes repository
  app/api/domains/cho.py
  app/repositories/client_hashes.py
Labels: enhancement, code quality

#598 refactor: favourites repository
  app/api/domains/osu.py
  app/repositories/favourites.py
Labels: enhancement, code quality

#599 refactor: ratings repository
  app/api/domains/osu.py
  app/objects/beatmap.py
  app/repositories/ratings.py
Labels: enhancement, code quality

#600 Gracefully handle no match host on lobby join case; add debug logs
  app/api/domains/cho.py
  app/objects/match.py
Labels: bug

#607 fix: add rounding to score on getscores
  app/api/domains/osu.py
Labels: bug

#596 Mock achievement downloads in tests (2x speedup to suite)
  tests/conftest.py
Labels: performance

#610 Simplify the `Player` object/class
  app/api/domains/cho.py
  app/objects/collections.py
  app/objects/player.py
Labels: code quality

#609 Setup test coverage (text & html reports available in CI)
  .github/workflows/test.yaml
  .gitignore
  poetry.lock
  pyproject.toml
  scripts/run-tests.sh
Labels: enhancement, dependencies, developer tooling

#597 Split `MapPools` and related collections/cache into repositories
  app/api/v1/api.py
  app/commands.py
  app/objects/collections.py
  app/objects/match.py
  app/repositories/tourney_pool_maps.py
  app/repositories/tourney_pools.py
  app/state/sessions.py
Labels: code quality

#615 Migrate beatmap objects off kwargs (& fix bugs found from migration)
  app/objects/beatmap.py
  app/repositories/maps.py
Labels: bug, code quality

#612 Remove unnecessary features to decrease maintenance/complexity overhead. + Cleanup & more repo usage.
  app/api/domains/osu.py
  app/api/init_api.py
  app/bg_loops.py
  app/commands.py
  app/constants/clientflags.py
  app/constants/gamemodes.py
  app/constants/mods.py
  app/constants/privileges.py
  app/constants/regexes.py
  app/discord.py
  app/objects/achievement.py
  app/objects/channel.py
  app/objects/clan.py
  app/objects/player.py
  app/settings.py
  app/utils.py
  docker-compose.test.yml
  docker-compose.yml
  ext/Caddyfile
  ext/nginx.conf.example
  main.py
Labels: code quality

#616 Handle private match history case in match creation
  app/api/domains/cho.py
  app/objects/match.py
Labels: bug

#619 Deprecate clans collection, only hold clan id references & don't cache in memory
  app/api/domains/cho.py
  app/api/domains/osu.py
  app/api/v1/api.py
  app/commands.py
  app/objects/__init__.py
  app/objects/clan.py
  app/objects/collections.py
  app/objects/player.py
  app/repositories/clans.py
  app/state/sessions.py
  app/utils.py
Labels: code quality

#624 Fix migrations not running if never run before
  app/state/services.py
Labels: bug

#625 Basic indices for SQL
  migrations/base.sql
  migrations/migrations.sql
  pyproject.toml
Labels: performance

#630 Refactor scores, stats and channels repos to build queries with sqlalchemy core 1.4
  Makefile
  app/api/domains/osu.py
  app/commands.py
  app/repositories/__init__.py
  app/repositories/achievements.py
  app/repositories/channels.py
  app/repositories/scores.py
  app/repositories/stats.py
  poetry.lock
  pyproject.toml
Labels: performance, code quality

#634 Ensure `/get_mappool` doesn't crash if pool creator is not in a clan
  app/api/v1/api.py
Labels: bug

#632 [v5.1.0] Refactor the rest of the repositories to use sqlalchemy core 1.4
  app/adapters/__init__.py
  app/adapters/database.py
  app/api/domains/cho.py
  app/api/domains/osu.py
  app/api/v1/api.py
  app/commands.py
  app/objects/beatmap.py
  app/objects/player.py
  app/repositories/__init__.py
  app/repositories/achievements.py
  app/repositories/channels.py
  app/repositories/clans.py
  app/repositories/client_hashes.py
  app/repositories/comments.py
  app/repositories/favourites.py
  app/repositories/ingame_logins.py
  app/repositories/logs.py
  app/repositories/mail.py
  app/repositories/map_requests.py
  app/repositories/maps.py
  app/repositories/ratings.py
  app/repositories/scores.py
  app/repositories/stats.py
  app/repositories/tourney_pool_maps.py
  app/repositories/tourney_pools.py
  app/repositories/user_achievements.py
  app/repositories/users.py
  app/state/services.py
  app/usecases/user_achievements.py
  pyproject.toml
Labels: performance, code quality

#611 Low-lift solution to move to stdlib logging
  .env.example
  .github/docs/wiki/Setting-up.md
  .github/docs/wiki/locale/de-DE/Setting-up-de-DE.md
  .github/docs/wiki/locale/zh-CN/Setting-up-zh-CN.md
  .github/workflows/test.yaml
  .gitignore
  app/adapters/database.py
  app/api/domains/cho.py
  app/api/domains/osu.py
  app/api/init_api.py
  app/api/middlewares.py
  app/logging.py
  app/objects/player.py
  app/settings.py
  app/state/services.py
  app/utils.py
  docker-compose.test.yml
  docker-compose.yml
  logging.yaml.example
  main.py
  poetry.lock
  pyproject.toml
  tools/proxy.py
Labels: code quality, developer tooling

#479 fix: prevent crash when leaving tournament match channel
  app/api/domains/cho.py
Labels: bug

#643 Instrument & log all database calls
  app/adapters/database.py
  app/timer.py
Labels: developer tooling

#642 [v5.2.2] Significantly optimize performance for fetching leaderboards
  migrations/base.sql
  migrations/migrations.sql
  pyproject.toml
Labels: performance
